### ISSUE TITLE
转换时出现错误Cannot find module 'semver/functions/satisfies'

### ISSUE THREAD

**Issue by iamxiyang** [SyMind/taro2-to-3#1]
### 使用步骤：

在项目下执行
```
npm i -g taro2-to-3
```
接着执行

```
taro2-to-3
```
**出现以下错误：**
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'semver/functions/satisfies'
Require stack:
- C:\Users\Administrator\AppData\Roaming\npm\node_modules\taro2-to-3\bin\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\taro2-to-3\bin\cli.js:12:25)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\taro2-to-3\\bin\\cli.js'
  ]
}
```

### 环境信息：

```
npm -v
7.6.2

taro -v
� Taro v2.2.16
```

**Comment by iamxiyang** [comment]
期待大佬继续完善，如有需要帮助测试可以添加我的微信 64128498

**Comment by SyMind** [comment]
感谢反馈！很悲伤的一件事情，应该是由于我将 semver 依赖放置到了 devDependencies 中了导致的，但是我在本地测试时却并没有发现该问题，可能是我全局安装了这个依赖？（汗

**Comment by SyMind** [comment]
@iamxiyang 发布了 0.0.1-alpha.7 版本，并在本地清空了所有 npm 缓存进行全局安装测试，应该已经修复了，请尝试。

**Comment by iamxiyang** [comment]
> @iamxiyang 我发布了 0.0.1-alpha.7 版本，并在本地清空了所有 npm 缓存进行全局安装测试，应该已经修复了，请尝试。

@SyMind  我刚才尝试重新安装后执行命令，不再出现上面的错误了，但出现了新的错误。错误信息如下：


```
(node:13212) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at Project.transformConfig (C:\Users\Administrator\AppData\Roaming\npm\node_modules\taro2-to-3\bin\project.js:86:41)
    at bootstrap (C:\Users\Administrator\AppData\Roaming\npm\node_modules\taro2-to-3\bin\cli.js:299:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:13212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async func
tion without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handl
ed will terminate the Node.js process with a non-zero exit code.

```

**Comment by iamxiyang** [comment]
我尝试在报错的位置添加了一个判断，可以往下正常执行了。
但执行完成发现了一点问题：
@tarojs/taro-qq 这个依赖包没有处理。
所有 *.config.ts 的配置都没有被生成，还在页面中显示。
预加载this.$preloadData没有转换，最新的taro版本已支持预加载api。

**Comment by iamxiyang** [comment]
在转换时 @tarojs/plugin-sass 被移除了，但是 config/index.js 中的plugins里面没有被移除，尝试编译时会提示错误。

**Comment by SyMind** [comment]
> 预加载this.$preloadData没有转换，最新的taro版本已支持预加载api。

我们的项目没有使用这个 api，我周末将会进行这个 api 的转换。

其他的问题晚些我看一下，以下问题解决了。

> > @iamxiyang 我发布了 0.0.1-alpha.7 版本，并在本地清空了所有 npm 缓存进行全局安装测试，应该已经修复了，请尝试。
> 
> @SyMind 我刚才尝试重新安装后执行命令，不再出现上面的错误了，但出现了新的错误。错误信息如下：
> 
> ```
> (node:13212) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
>     at Project.transformConfig (C:\Users\Administrator\AppData\Roaming\npm\node_modules\taro2-to-3\bin\project.js:86:41)
>     at bootstrap (C:\Users\Administrator\AppData\Roaming\npm\node_modules\taro2-to-3\bin\cli.js:299:11)
>     at processTicksAndRejections (internal/process/task_queues.js:94:5)
> (node:13212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async func
> tion without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:13212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handl
> ed will terminate the Node.js process with a non-zero exit code.
> ```

**Comment by SyMind** [comment]
@iamxiyang 

> 预加载this.$preloadData没有转换，最新的taro版本已支持预加载api。

你好，请问这个 api taro 2.x -> taro 3.x 有变更么？我看 Taro 的文档貌似没有变化？我对这个 api 不了解，你能给我更多信息参考么？

**Comment by iamxiyang** [comment]
@SyMind 
> 你好，请问这个 api taro 2.x -> taro 3.x 有变更么？我看 Taro 的文档貌似没有变化？我对这个 api 不了解，你能给我更多信息参考么？

taro文档中只有2.x的信息，taro3.x的只能通过github的看到。

```
Taro 3 不再提供 componentWillPreload、$preload API，改为:
调用：
Taro.preload()
获取
console.log(getCurrentInstance().preloadData)
```

taro2参考：https://taro-docs.jd.com/taro/docs/optimized-practice#%E9%A2%84%E5%8A%A0%E8%BD%BD
taro3参考：https://github.com/NervJS/taro/commit/d2c4aaf5d9d755bc3ca40f9b449340b360c673d5

**Comment by SyMind** [comment]
@iamxiyang 看起来是在 taro 3.2.x 版本之后才会变更，当前不搞，下一周或大下周添加。

**Comment by iamxiyang** [comment]
@SyMind 

所有 *.config.ts 的配置都没有被生成，Config还在页面 *.tsx 中显示。

这个貌似还没处理？我刚才安装还是这样的。

**Comment by SyMind** [comment]
以上问题均已解决，该 issue 将关闭，若在使用过程中存在其他功能问题，请新建 issue。
