### ISSUE TITLE
执行的时候提示 Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mty-qw** [SyMind/taro2-to-3#4]
![image](https://user-images.githubusercontent.com/45986485/130432899-e9040f30-3b07-4c75-bb1a-7e7c545dc2d3.png)

**Comment by liminshen** [comment]
同问

**Comment by liminshen** [comment]
需要去掉config/index的第三方依赖

**Comment by SyMind** [comment]
抱歉才看到，我本周看一下。

**Comment by SyMind** [comment]
@mty-qw 能给予我更多的信息么？什么文件在什么情况下会有这个问题。
