### ISSUE TITLE
更新完，执行的时候编译报错：正在编译...Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by HappyYawen** [SyMind/taro2-to-3#6]

**Comment by SyMind** [comment]
@HappyYawen 这个错误 `error:0308010C:digital envelope routines::unsupported` 通常是在 Node.js 中出现的，尤其是在 Node.js 17 或更高版本中运行基于 OpenSSL 3.0 的代码时。这是因为 Node.js 17 开始使用 OpenSSL 3.0，而 OpenSSL 3.0 使用了默认的安全级别 2，这可能会导致某些加密算法不再被支持，进而抛出错误。

如果你的应用程序不能正确地运行在使用 OpenSSL 3.0 的 Node.js 版本，你可能需要降级到 Node.js 16 或更低版本，这些版本使用 OpenSSL 1.1.x。

**Comment by SyMind** [comment]
@HappyYawen 你好，有解决你的问题么？
